services:

  ${CORE_FRONTEND_SERVICE_NAME}:
    image: rer-frontend:latest
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - APP_VERSION=${APP_VERSION}
        - VITE_BASE_URL=/
        - VITE_DPG_URL=${HTTP_HTTPS}://${HOSTNAME_DNS}${BASE_URL}${CORE_BACKEND_API_CONTEXT_PATH}/${CORE_BACKEND_API_VERSION}
        - VITE_AUTH_MODULE_URL=${HTTP_HTTPS}://${HOSTNAME_DNS}${BASE_URL}/auth
        - VITE_CALCULATION_ENGINE_BASE_URL=${HTTP_HTTPS}://${HOSTNAME_DNS}${BASE_URL}${CALCULATION_ENGINE_API_BASE_URL}
        - VITE_GEOSERVER_URL=${HTTP_HTTPS}://${HOSTNAME_DNS}${BASE_URL}${GEOSERVER_BASE_URL}/wms
    container_name: ${CORE_FRONTEND_CONTAINER_NAME}
    restart: unless-stopped
    networks:
      # - frontend_network
      - gateway_network