services:

  ${CORE_FRONTEND_SERVICE_NAME}:
    image: rer-frontend:latest
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - APP_VERSION=${APP_VERSION}
    container_name: ${CORE_FRONTEND_CONTAINER_NAME}
    restart: unless-stopped
    networks:
      # - frontend_network
      - gateway_network